"""parameter option sources

Revision ID: 467dbe39c141
Revises: 5f99417e43b1
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '467dbe39c141'
down_revision: str | None = '5f99417e43b1'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter_spec', sa.Column('options_from', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameter_spec', 'options_from')
    # ### end Alembic commands ###
