"""identite d un champ par position

Revision ID: 51d5064b92b3
Revises: c9a4a1fb75fb
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '51d5064b92b3'
down_revision: str | None = 'c9a4a1fb75fb'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dataset', 'dataset_version', ['current_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_constraint(op.f('ux_field_spec_name'), 'field_spec', type_='unique')
    op.create_unique_constraint('ux_field_spec_position', 'field_spec', ['data_spec_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_field_spec_position', 'field_spec', type_='unique')
    op.create_unique_constraint(op.f('ux_field_spec_name'), 'field_spec', ['data_spec_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    # ### end Alembic commands ###
