"""scenario parameter catalog

Revision ID: 5f99417e43b1
Revises: 51d5064b92b3
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5f99417e43b1'
down_revision: str | None = '51d5064b92b3'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_spec',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('group', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('default', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_values', sa.Text(), nullable=True),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_parameter_spec_group'), 'parameter_spec', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parameter_spec_group'), table_name='parameter_spec')
    op.drop_table('parameter_spec')
    # ### end Alembic commands ###
