"""parameter activation conditions

Revision ID: ae3a19d7af44
Revises: 3cb378e3a9cf
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ae3a19d7af44'
down_revision: str | None = '3cb378e3a9cf'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter_spec', sa.Column('enabled_if', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameter_spec', 'enabled_if')
    # ### end Alembic commands ###
